name = "FixedShapeDistributions"
uuid = "c4c428b9-93a0-4b19-ba3b-79994e5a3653"
authors = ["Andrew Black"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
